### ISSUE TITLE
Produção do Rich Picture

### ISSUE THREAD

**Issue by analeticiaa** [Requisitos-de-Software/2023.2-LibreOffice#11]
Um Rich Picture é uma representação gráfica informal e rica em detalhes que ajuda a visualizar e compreender problemas complexos, sistemas ou situações. Será usado para facilitar a comunicação e a resolução de problemas relacionados ao aplicativo escolhido. Pode incluir desenhos, símbolos e anotações para capturar informações relevantes.

**Comment by raphaiela** [comment]
Versão 1 do rich picture
![image](https://github.com/Requisitos-de-Software/2023.2-LibreOffice/assets/64171633/ab2b4b66-e617-4368-ab51-9e6398a87146)

**Comment by analeticiaa** [comment]
O Rich Picture que vc enviou contém os 5 elementos necessários, mas minha sugestão é modificar um pouquinho:
- Atores: modificar o segundo usuário por leitor/colaborador
- Operações: colocar as operações "inserir", "editar" e "formatar" no lado esquerdo, próximo ao usuário e dentro de um círculo
- Data Store: fazer uma abstração para "arquivo"
- Fluxo: inserir um computador para representar que os dados estão sendo salvos localmente ou remotamente (no caso da internet)
- Limite do sistema: incluir o compartilhamento (nessa parte estou com dúvidas)


![image](https://github.com/Requisitos-de-Software/2023.2-LibreOffice/assets/56135971/766c7bfc-1235-46a2-91a7-eea063a6056b)

**Comment by analeticiaa** [comment]
O Rich Picture que vc enviou contém todos os 5 elementos necessários, mas minha sugestão é modificar um pouquinho:

- Atores: modificar o segundo usuário por leitor/colaborador
- Operações: colocar as operações "inserir", "editar" e "formatar" no lado esquerdo, próximo ao usuário e dentro de um círculo
- Data Store: fazer uma abstração para "arquivo"
- Fluxo: inserir um computador para representar que os dados estão sendo salvos localmente ou remotamente (no caso da internet)
- Limite do sistema: manter


![image](https://github.com/Requisitos-de-Software/2023.2-LibreOffice/assets/56135971/137b7c4a-5f22-4676-b79a-e14629c03bca)

Observação: também precisamos escrever uma legenda depois

**Comment by raphaiela** [comment]
Perfeito, vamos fechar assim
